In [12]:
import pandas as pd
from tqdm import tqdm

In [8]:
df = pd.read_csv('df_estado.csv')
df.head()

,STATE,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024,NPOPCHG2020,NPOPCHG2021,NPOPCHG2022,...,NETMIG2020,NETMIG2021,NETMIG2022,NETMIG2023,NETMIG2024,RESIDUAL2020,RESIDUAL2021,RESIDUAL2022,RESIDUAL2023,RESIDUAL2024
0,AK,1080382,1079782,1082544,1084470,1088238,1094826,-600,2762,1926,...,-2398,-3102,-2522,-1706,1012,-36,-170,-32,-10,-20
1,AL,9139847,9157448,9195228,9251407,9335087,9415717,17601,37780,56179,...,20569,54304,69717,83174,80349,-1684,1819,-386,168,-37
2,AR,4801626,4809582,4836980,4882238,4926455,4968394,7956,27398,45258,...,6271,29715,46565,40113,36753,551,727,-109,157,81
3,AZ,14131942,14190228,14365782,14572440,14763422,14982364,58286,175554,206658,...,60914,183662,202782,175268,198322,-3082,-186,3864,-770,606
4,CA,96550904,96453685,95352868,95271790,95375395,95922475,-97219,-1100817,-81078,...,-172483,-1214832,-327982,-155680,277866,8261,-41185,-6777,3314,1492

Nesse dataframe faremos duas coisas: 
* Modificar a sigla do estado para o nome do estado.
* Adicionar uma coluna com os dados de colunas de mortalidade e natalidade relativos à população do estado.

## Modificando a sigla para o nome

In [4]:
STATES = {
    'TX': 'Texas',
    'CA': 'California',
    'FL': 'Florida',
    'NY': 'New York',
    'PA': 'Pennsylvania',
    'IL': 'Illinois',
    'OH': 'Ohio',
    'GA': 'Georgia',
    'NC': 'North Carolina',
    'MI': 'Michigan',
    'NJ': 'New Jersey',
    'VA': 'Virginia',
    'WA': 'Washington',
    'AZ': 'Arizona',
    'MA': 'Massachusetts',
    'TN': 'Tennessee',
    'IN': 'Indiana',
    'MO': 'Missouri',
    'MD': 'Maryland',
    'WI': 'Wisconsin',
    'CO': 'Colorado',
    'MN': 'Minnesota',
    'SC': 'South Carolina',
    'AL': 'Alabama',
    'LA': 'Louisiana',
    'KY': 'Kentucky',
    'OR': 'Oregon',
    'OK': 'Oklahoma',
    'CT': 'Connecticut',
    'IA': 'Iowa',
    'MS': 'Mississippi',
    'AR': 'Arkansas',
    'KS': 'Kansas',
    'UT': 'Utah',
    'NV': 'Nevada',
    'NM': 'New Mexico',
    'NE': 'Nebraska',
    'WV': 'West Virginia',
    'ID': 'Idaho',
    'HI': 'Hawaii',
    'NH': 'New Hampshire',
    'ME': 'Maine',
    'RI': 'Rhode Island',
    'MT': 'Montana',
    'DE': 'Delaware',
    'SD': 'South Dakota',
    'ND': 'North Dakota',
    'AK': 'Alaska',
    'VT': 'Vermont',
    'WY': 'Wyoming',
    'DC': 'District of Columbia',
    'PR': 'Puerto Rico',
}

In [9]:
for index, row in df.iterrows():
    state = row['STATE']
    df.at[index, 'STATE'] = STATES[state]
df.head()

,STATE,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024,NPOPCHG2020,NPOPCHG2021,NPOPCHG2022,...,NETMIG2020,NETMIG2021,NETMIG2022,NETMIG2023,NETMIG2024,RESIDUAL2020,RESIDUAL2021,RESIDUAL2022,RESIDUAL2023,RESIDUAL2024
0,Alaska,1080382,1079782,1082544,1084470,1088238,1094826,-600,2762,1926,...,-2398,-3102,-2522,-1706,1012,-36,-170,-32,-10,-20
1,Alabama,9139847,9157448,9195228,9251407,9335087,9415717,17601,37780,56179,...,20569,54304,69717,83174,80349,-1684,1819,-386,168,-37
2,Arkansas,4801626,4809582,4836980,4882238,4926455,4968394,7956,27398,45258,...,6271,29715,46565,40113,36753,551,727,-109,157,81
3,Arizona,14131942,14190228,14365782,14572440,14763422,14982364,58286,175554,206658,...,60914,183662,202782,175268,198322,-3082,-186,3864,-770,606
4,California,96550904,96453685,95352868,95271790,95375395,95922475,-97219,-1100817,-81078,...,-172483,-1214832,-327982,-155680,277866,8261,-41185,-6777,3314,1492

## Adicionando a coluna com os dados relativos

In [10]:
df.columns

Index(['STATE', 'ESTIMATESBASE2020', 'POPESTIMATE2020', 'POPESTIMATE2021',
       'POPESTIMATE2022', 'POPESTIMATE2023', 'POPESTIMATE2024', 'NPOPCHG2020',
       'NPOPCHG2021', 'NPOPCHG2022', 'NPOPCHG2023', 'NPOPCHG2024',
       'BIRTHS2020', 'BIRTHS2021', 'BIRTHS2022', 'BIRTHS2023', 'BIRTHS2024',
       'DEATHS2020', 'DEATHS2021', 'DEATHS2022', 'DEATHS2023', 'DEATHS2024',
       'NATURALCHG2020', 'NATURALCHG2021', 'NATURALCHG2022', 'NATURALCHG2023',
       'NATURALCHG2024', 'INTERNATIONALMIG2020', 'INTERNATIONALMIG2021',
       'INTERNATIONALMIG2022', 'INTERNATIONALMIG2023', 'INTERNATIONALMIG2024',
       'DOMESTICMIG2020', 'DOMESTICMIG2021', 'DOMESTICMIG2022',
       'DOMESTICMIG2023', 'DOMESTICMIG2024', 'NETMIG2020', 'NETMIG2021',
       'NETMIG2022', 'NETMIG2023', 'NETMIG2024', 'RESIDUAL2020',
       'RESIDUAL2021', 'RESIDUAL2022', 'RESIDUAL2023', 'RESIDUAL2024'],
      dtype='object')

In [13]:
years = ['2020', '2021', '2022', '2023', '2024']
columns = ['BIRTHS', 'DEATHS']
for year in years:
    pop_column = f'POPESTIMATE{year}'
    for col in columns:
        column = f'{col}{year}'
        new_column = f'{col}PER1000HABITANTS{year}'
        df[new_column] = 0.0 
        for index, row in tqdm(df.iterrows(),total=df.shape[0]):
            value = row[column]
            population = row[pop_column]
            relative_value = (value / population) * 1000  # per 1000 people
            
            df.at[index, new_column] = relative_value
            
df.head()

100%|██████████| 51/51 [00:00<00:00, 11549.57it/s]
100%|██████████| 51/51 [00:00<00:00, 12976.80it/s]
  0%|          | 0/51 [00:00<?, ?it/s]

100%|██████████| 51/51 [00:00<00:00, 9503.29it/s]
100%|██████████| 51/51 [00:00<00:00, 13640.45it/s]
100%|██████████| 51/51 [00:00<00:00, 11768.79it/s]
100%|██████████| 51/51 [00:00<00:00, 11410.33it/s]
100%|██████████| 51/51 [00:00<00:00, 11712.08it/s]
100%|██████████| 51/51 [00:00<00:00, 11825.39it/s]
100%|██████████| 51/51 [00:00<00:00, 11650.21it/s]
100%|██████████| 51/51 [00:00<00:00, 9495.27it/s]

,STATE,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024,NPOPCHG2020,NPOPCHG2021,NPOPCHG2022,...,BIRTHSPER1000HABITANTS2020,DEATHSPER1000HABITANTS2020,BIRTHSPER1000HABITANTS2021,DEATHSPER1000HABITANTS2021,BIRTHSPER1000HABITANTS2022,DEATHSPER1000HABITANTS2022,BIRTHSPER1000HABITANTS2023,DEATHSPER1000HABITANTS2023,BIRTHSPER1000HABITANTS2024,DEATHSPER1000HABITANTS2024
0,Alaska,1080382,1079782,1082544,1084470,1088238,1094826,-600,2762,1926,...,3.246952,1.548461,12.557457,6.983550,12.542532,8.411482,12.409050,7.369711,12.306978,7.195664
1,Alabama,9139847,9157448,9195228,9251407,9335087,9415717,17601,37780,56179,...,2.767474,2.907688,11.312824,13.307663,11.447988,12.869610,11.429781,11.393574,11.209874,11.176101
2,Arkansas,4801626,4809582,4836980,4882238,4926455,4968394,7956,27398,45258,...,2.881331,2.645552,11.706271,12.335590,12.068031,12.313410,11.762819,10.961635,11.689693,10.662198
3,Arizona,14131942,14190228,14365782,14572440,14763422,14982364,58286,175554,206658,...,2.509614,2.477621,10.396232,10.947681,10.732039,10.731216,10.519783,9.403240,10.327075,8.991238
4,California,96550904,96453685,95352868,95271790,95375395,95922475,-97219,-1100817,-81078,...,2.575143,1.880478,10.386798,8.759160,10.675920,8.013211,10.340780,7.656954,10.056882,7.265857

In [ ]:
df.to_csv('df_modificado.csv', index=False)